#+TITLE:        README
#+AUTHOR:       Pedro Chinen

* Dotfiles-Emacs

Emacs Configuration for my personal use. The `C-x` keystroke was giving
me the pinky problem so I create an alternative for it `M-v` without
removing the `C-x` neither the `M-x`.

* How to Install

Clone the repository / fork it /  or just download it:

#+BEGIN_SRC sh
  git clone https://github.com/chinen93/dotfiles-emacs.git
#+END_SRC

** Linux

Execute the /install.sh/

#+BEGIN_SRC sh
  ./install.sh
#+END_SRC

What this shell script does is create a soft link between your home
directory and this configurations directory.

** Windows

#+BEGIN_SRC sh
  install_windows.bat
#+END_SRC

What this shell script does is copy from this configuration
directory and the .emacs.d folder in your windows computer.

#+BEGIN_SRC sh
  update_git_folder_windows.bat
#+END_SRC

And this other script copy back your .emacs.d directory to your
git directory. Usefull to push your changes to git.

* How the files are stored
** files/emacsConfig/

All the configurations files are stored here. They have this format
/init-PACKAGE.el/ where *PACKAGE* is the mode or package the
configurations is about.

Most of the packages are installed and configurated using
[[https://github.com/jwiegley/use-package][use-package]]. However, there are some that are built-in emacs and don't
need this kind of installation.

Because I couldn't find a way to install packages easily on Windows, I
just use the built-ins and the ones that only use pure elisp.

** files/emacsSnippets/

Snippets for [[https://joaotavora.github.io/yasnippet/][Yasnippet]] are here. I didn't use the default snippets
because I wanted to experience without them first so I could really
get only the ones I needed.

** files/emacs

This file is only for loading my others configurations files. It is
the first file that emacs opens. And the default file when
configurations are made using the **customize** functions.
