#!/bin/bash
#
# Author: `user-full-name` <`user-mail-address`>
# File: `(upcase (file-name-nondirectory (file-name-sans-extension (buffer-file-name))))`
# Copyright © `(format-time-string "%Y")`, `user-full-name`, all rights reserved.
# Created: `(format-time-string "%e %B %Y")`
#

$0

# `(file-name-nondirectory (buffer-file-name))` ends here