#+TITLE:        Ivy Configuration
#+AUTHOR:       Pedro Chinen
#+DATE-CREATED: [2018-09-22 Sat]
#+DATE-UPDATED: [2019-09-22 dom]

Emacs is a text editor which don't want to bother the user. So
normally it doesn't have an auto completion function. However for
editing text is important to have some sort of help. That one reason
for using a completion package is essential to make it a better
environment.

One of those packages is the [[https://github.com/abo-abo/swiper][Ivy]] with its [[https://oremacs.com/swiper/][manual]]. I'll let it
introduce itself:

Ivy is an interactive interface for completion in Emacs. Emacs uses
completion mechanism in a variety of contexts: code, menus, commands,
variables, functions, etc. Completion entails listing, sorting,
filtering, previewing, and applying actions on selected items. When
active, ivy-mode completes the selection process by narrowing
available choices while previewing in the mini buffer. Selecting the
final candidate is either through simple keyboard character inputs or
through powerful regular expressions.

#+BEGIN_SRC emacs-lisp
  (require-package 'ivy)
  (require-package 'counsel)

  (ivy-mode 1)

#+END_SRC

* Configure
:PROPERTIES:
:ID:       efbd1606-eff7-43a5-a4e6-8c12b6d229ef
:END:

Number of result lines to display
#+BEGIN_SRC emacs-lisp
  (setq ivy-height 10)
#+END_SRC

Does not count candidates
#+BEGIN_SRC emacs-lisp
  (setq ivy-count-format "")

#+END_SRC

No regexp by default
#+BEGIN_SRC emacs-lisp
  (setq ivy-initial-inputs-alist nil)

#+END_SRC

Configure regexp engine.
#+BEGIN_SRC emacs-lisp
  (setq ivy-re-builders-alist
	;; allow input not in order
	'((t   . ivy--regex-ignore-order)))

#+END_SRC

* Provide File
:PROPERTIES:
:ID:       0a01efe1-3948-4017-b344-38ecef7b2a48
:END:
#+BEGIN_SRC emacs-lisp
  (provide 'init-ivy)
#+END_SRC



