#+TITLE:        Backup Configuration
#+AUTHOR:       Pedro Chinen
#+DATE-CREATED: [2018-09-22 Sat]
#+DATE-UPDATED: [2023-10-04 Wed]

Backup is a important part of editing text. Because most of times I
make some mistakes and the possibility to revert to a cleaner state is
the best thing ever.

* Provide File
:PROPERTIES:
:ID:       0a01efe1-3948-4017-b344-38ecef7b2a48
:END:
#+BEGIN_SRC emacs-lisp
  (provide 'init-backup)
#+END_SRC

* Set Default Directory
:PROPERTIES:
:ID:       a5f317bc-1b74-410b-89fb-07ebeb91b44f
:END:

The default directory to store backups is the file's directory that is
being edited. However, for me, it makes the directory kind of
messy. So to tidy it up a bit I put everything inside a previously set
path.

#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist `(("." . ,my/backup-folder)))
#+END_SRC

* DONE How to put every auto-saved backup files into a single directory
CLOSED: [2019-03-15 sex 18:49]
:PROPERTIES:
:ID:       b46630ef-a0a3-4ec3-8d47-104c057070cb
:END:
- State "DONE"       from "WORKING"    [2019-03-15 sex 18:49]
- State "WORKING"    from "TODO"       [2019-03-15 sex 18:49]

*auto-save-file-name-transforms* is a set of transformations that
happens to each file before making an auto-save file name. Because the
REGEXP is tied to ".*" it means that all files will be transformed by
this function. In this case, the REGEXP expression replacement is the
complete path to a specific directory, which means that every
auto-saved file will go into the same directory.

#+BEGIN_SRC emacs-lisp
  (setq auto-save-file-name-transforms `((".*" ,my/auto-save-folder t)))
#+END_SRC

* Configurations
:PROPERTIES:
:ID:       bb2f8725-32f0-44af-ac1c-ca45a9565b0b
:END:

Copy the file to the backup's folder.
#+BEGIN_SRC emacs-lisp
  (setq backup-by-copying t)

#+END_SRC

When making a backup create a name with a numeric suffix like:
#+BEGIN_SRC text
  Organizador.org.~1~
  Organizador.org.~2~
  Organizador.org.~4~
#+END_SRC

Create numeric suffix when backing up files. I make this way because I
can see what was changed between edits. And It does not take much
space in disk.
#+BEGIN_SRC emacs-lisp
  (setq version-control t)

#+END_SRC

But don't keep too many versions. Just some.
#+BEGIN_SRC emacs-lisp
  ;; How many backups to keep
  (setq kept-new-versions 2)
  (setq kept-old-versions 2)

  ;; Delete the others
  (setq delete-old-versions t)

#+END_SRC
