#+TITLE:        Yasnippet Configurations
#+AUTHOR:       Pedro Chinen
#+DATE-CREATED: [2018-09-23 Sun]
#+DATE-UPDATED: [2019-04-25 qui]

YASnippet is a template system for Emacs. It allows you to type an abbreviation and automatically expand it into function templates. Bundled language templates include: C, C++, C#, Perl, Python, Ruby, SQL, LaTeX, HTML, CSS and more.

https://joaotavora.github.io/yasnippet/

Load package to be used in this condfiguration.
#+BEGIN_SRC emacs-lisp
  (require-package 'yasnippet)

  (message "Yasnippet - Loaded")

#+END_SRC

*  Snippets Location
:PROPERTIES:
:ID:       bb384859-63d5-4e82-a43d-ff9e341de4f0
:END:

My default snippets folder is in *~/emacsSnippets*.
#+BEGIN_SRC emacs-lisp
  (let* ((folder "emacsSnippets/")
         (default (concat "~/" folder)))

    ;; Default directories to seek for snippets
    (setq yas-snippet-dirs
          ;; Personal Collection
          `(,default))

    ;; If the home folder is in another place
    (when (and (boundp 'my/home-folder)
               (file-directory-p my/home-folder))
      (setq yas-snippet-dirs
            `(,(concat my/home-folder folder)))))

#+END_SRC

And they are organized in a specific order, where /printf/, /for/, /while/, /println/, /email/, /time/ are snippets in their respectivly mode directories.
#+BEGIN_SRC text
  .
  |-- c-mode
  |   |-- .yas-parents    # contains "cc-mode text-mode"
  |   `-- printf
  |-- cc-mode
  |   |-- for
  |   `-- while
  |-- java-mode
  |   |-- .yas-parents    # contains "cc-mode text-mode"
  |   `-- println
  `-- text-mode
      |-- email
      `-- time
#+END_SRC

*.yas-parents* is a file that contains, a whitespace-separated, list with mode names. It represents that those modes have shared snippets. So in the last example when you are in the c-mode you can also use cc-mode and text-mode snippets.

* Configuration
:PROPERTIES:
:ID:       505528f7-f256-4161-8fc8-2cba26a63e05
:END:

Surppress yasnippet backquote changes.
#+BEGIN_SRC emacs-lisp
  (setq warning-suppress-types '(yasnippet backquote-change))

#+END_SRC

Controls indenting applied to snippets. Indent the snippet to the current column.
#+BEGIN_SRC emacs-lisp
  (setq yas-indent-line 'fixed)

#+END_SRC

* Enable Yasnippets Globally
:PROPERTIES:
:ID:       55addacd-953a-4a5a-b734-1ad0584f6db0
:END:
#+BEGIN_SRC emacs-lisp
  ;; Enable yasnippet mode globally
  (yas-global-mode)

#+END_SRC

